// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: gateway_service.proto

package gateway

import (
	_go "github.com/gruspost-dot/contracts/account/go"
	_go1 "github.com/gruspost-dot/contracts/auth/go"
	_go2 "github.com/gruspost-dot/contracts/pagination/go"
	_go3 "github.com/gruspost-dot/contracts/transaction/go"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запросы для аутентификации
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`         // профиль из account
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // пароль как отдельное поле
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gateway_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *_go1.TokenPair        `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gateway_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetTokens() *_go1.TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginOrEmail  string                 `protobuf:"bytes,1,opt,name=login_or_email,json=loginOrEmail,proto3" json:"login_or_email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gateway_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLoginOrEmail() string {
	if x != nil {
		return x.LoginOrEmail
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *_go1.TokenPair        `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gateway_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetTokens() *_go1.TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_gateway_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_gateway_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_gateway_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_gateway_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// Запросы для управления пользователями
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.CreateUser        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_gateway_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserRequest) GetUser() *_go.CreateUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_gateway_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_gateway_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserResponse) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_gateway_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentUserResponse) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *_go2.Pagination       `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_gateway_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetUsersRequest) GetPagination() *_go2.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*_go.User            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *_go2.Pagination       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_gateway_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUsersResponse) GetUsers() []*_go.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersResponse) GetPagination() *_go2.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *_go.User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_gateway_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *_go.User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrentUserRequest) Reset() {
	*x = UpdateCurrentUserRequest{}
	mi := &file_gateway_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrentUserRequest) ProtoMessage() {}

func (x *UpdateCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCurrentUserRequest) GetUser() *_go.User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_gateway_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *_go1.TokenPair        `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_gateway_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshResponse) GetTokenPair() *_go1.TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

// Запросы для транзакций
type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_gateway_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{18}
}

func (x *DepositRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_gateway_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{19}
}

func (x *WithdrawRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient     uint64                 `protobuf:"varint,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_gateway_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{20}
}

func (x *TransferRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetRecipient() uint64 {
	if x != nil {
		return x.Recipient
	}
	return 0
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"` // фильтр по дате от
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`       // фильтр по дате до
	Pagination    *_go2.Pagination       `protobuf:"bytes,6,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_gateway_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransactionsRequest) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetTransactionsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetTransactionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetTransactionsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetTransactionsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetTransactionsRequest) GetPagination() *_go2.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Transactions  []*_go3.TransactionDetails `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_gateway_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetTransactionsResponse) GetTransactions() []*_go3.TransactionDetails {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_gateway_service_proto protoreflect.FileDescriptor

const file_gateway_service_proto_rawDesc = "" +
	"\n" +
	"\x15gateway_service.proto\x12\agateway\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bpagination/pagination.proto\x1a\x1baccount/account_model.proto\x1a\x15auth/auth_model.proto\x1a#transaction/transaction_model.proto\"P\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"^\n" +
	"\x10RegisterResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\x12'\n" +
	"\x06tokens\x18\x02 \x01(\v2\x0f.auth.TokenPairR\x06tokens\"P\n" +
	"\fLoginRequest\x12$\n" +
	"\x0elogin_or_email\x18\x01 \x01(\tR\floginOrEmail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\rLoginResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\x12'\n" +
	"\x06tokens\x18\x02 \x01(\v2\x0f.auth.TokenPairR\x06tokens\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"K\n" +
	"\x15ValidateTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\"<\n" +
	"\x11CreateUserRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.account.CreateUserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\";\n" +
	"\x16GetCurrentUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\"I\n" +
	"\x0fGetUsersRequest\x126\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x16.pagination.PaginationR\n" +
	"pagination\"o\n" +
	"\x10GetUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.account.UserR\x05users\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.pagination.PaginationR\n" +
	"pagination\"O\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.account.UserR\x04user\"=\n" +
	"\x18UpdateCurrentUserRequest\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.account.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"A\n" +
	"\x0fRefreshResponse\x12.\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x0f.auth.TokenPairR\ttokenPair\"A\n" +
	"\x0eDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"B\n" +
	"\x0fWithdrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"`\n" +
	"\x0fTransferRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\x04R\trecipient\"\xea\x02\n" +
	"\x16GetTransactionsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x04H\x00R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01\x12<\n" +
	"\tdate_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\bdateFrom\x88\x01\x01\x128\n" +
	"\adate_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x06dateTo\x88\x01\x01\x12;\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2\x16.pagination.PaginationH\x05R\n" +
	"pagination\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_typeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\r\n" +
	"\v_pagination\"^\n" +
	"\x17GetTransactionsResponse\x12C\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1f.transaction.TransactionDetailsR\ftransactions2\xa4\r\n" +
	"\aGateway\x12a\n" +
	"\bRegister\x12\x18.gateway.RegisterRequest\x1a\x19.gateway.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12U\n" +
	"\x05Login\x12\x15.gateway.LoginRequest\x1a\x16.gateway.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12]\n" +
	"\aRefresh\x12\x17.gateway.RefreshRequest\x1a\x18.gateway.RefreshResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12X\n" +
	"\x06Logout\x12\x16.gateway.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12p\n" +
	"\rValidateToken\x12\x1d.gateway.ValidateTokenRequest\x1a\x1e.gateway.ValidateTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/validate\x12Z\n" +
	"\n" +
	"CreateUser\x12\x1a.gateway.CreateUserRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12]\n" +
	"\aGetUser\x12\x17.gateway.GetUserRequest\x1a\x18.gateway.GetUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/users/{user_id}\x12c\n" +
	"\x0eGetCurrentUser\x12\x16.google.protobuf.Empty\x1a\x1f.gateway.GetCurrentUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/users/me\x12V\n" +
	"\bGetUsers\x12\x18.gateway.GetUsersRequest\x1a\x19.gateway.GetUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12d\n" +
	"\n" +
	"UpdateUser\x12\x1a.gateway.UpdateUserRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/users/{user_id}\x12k\n" +
	"\x11UpdateCurrentUser\x12!.gateway.UpdateCurrentUserRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/api/v1/users/me\x12a\n" +
	"\n" +
	"DeleteUser\x12\x1a.gateway.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/users/{user_id}\x12]\n" +
	"\x11DeleteCurrentUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/api/v1/users/me\x12c\n" +
	"\aDeposit\x12\x17.gateway.DepositRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/transactions/deposit\x12f\n" +
	"\bWithdraw\x12\x18.gateway.WithdrawRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/transactions/withdraw\x12f\n" +
	"\bTransfer\x12\x18.gateway.TransferRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/transactions/transfer\x12r\n" +
	"\x0fGetTransactions\x12\x1f.gateway.GetTransactionsRequest\x1a .gateway.GetTransactionsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/transactionsB6Z4github.com/gruspost-dot/contracts/gateway/go;gatewayb\x06proto3"

var (
	file_gateway_service_proto_rawDescOnce sync.Once
	file_gateway_service_proto_rawDescData []byte
)

func file_gateway_service_proto_rawDescGZIP() []byte {
	file_gateway_service_proto_rawDescOnce.Do(func() {
		file_gateway_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_service_proto_rawDesc), len(file_gateway_service_proto_rawDesc)))
	})
	return file_gateway_service_proto_rawDescData
}

var file_gateway_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_gateway_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: gateway.RegisterRequest
	(*RegisterResponse)(nil),         // 1: gateway.RegisterResponse
	(*LoginRequest)(nil),             // 2: gateway.LoginRequest
	(*LoginResponse)(nil),            // 3: gateway.LoginResponse
	(*RefreshRequest)(nil),           // 4: gateway.RefreshRequest
	(*LogoutRequest)(nil),            // 5: gateway.LogoutRequest
	(*ValidateTokenRequest)(nil),     // 6: gateway.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),    // 7: gateway.ValidateTokenResponse
	(*CreateUserRequest)(nil),        // 8: gateway.CreateUserRequest
	(*GetUserRequest)(nil),           // 9: gateway.GetUserRequest
	(*GetUserResponse)(nil),          // 10: gateway.GetUserResponse
	(*GetCurrentUserResponse)(nil),   // 11: gateway.GetCurrentUserResponse
	(*GetUsersRequest)(nil),          // 12: gateway.GetUsersRequest
	(*GetUsersResponse)(nil),         // 13: gateway.GetUsersResponse
	(*UpdateUserRequest)(nil),        // 14: gateway.UpdateUserRequest
	(*UpdateCurrentUserRequest)(nil), // 15: gateway.UpdateCurrentUserRequest
	(*DeleteUserRequest)(nil),        // 16: gateway.DeleteUserRequest
	(*RefreshResponse)(nil),          // 17: gateway.RefreshResponse
	(*DepositRequest)(nil),           // 18: gateway.DepositRequest
	(*WithdrawRequest)(nil),          // 19: gateway.WithdrawRequest
	(*TransferRequest)(nil),          // 20: gateway.TransferRequest
	(*GetTransactionsRequest)(nil),   // 21: gateway.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),  // 22: gateway.GetTransactionsResponse
	(*_go.User)(nil),                 // 23: account.User
	(*_go1.TokenPair)(nil),           // 24: auth.TokenPair
	(*_go.CreateUser)(nil),           // 25: account.CreateUser
	(*_go2.Pagination)(nil),          // 26: pagination.Pagination
	(*timestamppb.Timestamp)(nil),    // 27: google.protobuf.Timestamp
	(*_go3.TransactionDetails)(nil),  // 28: transaction.TransactionDetails
	(*emptypb.Empty)(nil),            // 29: google.protobuf.Empty
}
var file_gateway_service_proto_depIdxs = []int32{
	23, // 0: gateway.RegisterRequest.user:type_name -> account.User
	23, // 1: gateway.RegisterResponse.user:type_name -> account.User
	24, // 2: gateway.RegisterResponse.tokens:type_name -> auth.TokenPair
	23, // 3: gateway.LoginResponse.user:type_name -> account.User
	24, // 4: gateway.LoginResponse.tokens:type_name -> auth.TokenPair
	25, // 5: gateway.CreateUserRequest.user:type_name -> account.CreateUser
	23, // 6: gateway.GetUserResponse.user:type_name -> account.User
	23, // 7: gateway.GetCurrentUserResponse.user:type_name -> account.User
	26, // 8: gateway.GetUsersRequest.pagination:type_name -> pagination.Pagination
	23, // 9: gateway.GetUsersResponse.users:type_name -> account.User
	26, // 10: gateway.GetUsersResponse.pagination:type_name -> pagination.Pagination
	23, // 11: gateway.UpdateUserRequest.user:type_name -> account.User
	23, // 12: gateway.UpdateCurrentUserRequest.user:type_name -> account.User
	24, // 13: gateway.RefreshResponse.token_pair:type_name -> auth.TokenPair
	27, // 14: gateway.GetTransactionsRequest.date_from:type_name -> google.protobuf.Timestamp
	27, // 15: gateway.GetTransactionsRequest.date_to:type_name -> google.protobuf.Timestamp
	26, // 16: gateway.GetTransactionsRequest.pagination:type_name -> pagination.Pagination
	28, // 17: gateway.GetTransactionsResponse.transactions:type_name -> transaction.TransactionDetails
	0,  // 18: gateway.Gateway.Register:input_type -> gateway.RegisterRequest
	2,  // 19: gateway.Gateway.Login:input_type -> gateway.LoginRequest
	4,  // 20: gateway.Gateway.Refresh:input_type -> gateway.RefreshRequest
	5,  // 21: gateway.Gateway.Logout:input_type -> gateway.LogoutRequest
	6,  // 22: gateway.Gateway.ValidateToken:input_type -> gateway.ValidateTokenRequest
	8,  // 23: gateway.Gateway.CreateUser:input_type -> gateway.CreateUserRequest
	9,  // 24: gateway.Gateway.GetUser:input_type -> gateway.GetUserRequest
	29, // 25: gateway.Gateway.GetCurrentUser:input_type -> google.protobuf.Empty
	12, // 26: gateway.Gateway.GetUsers:input_type -> gateway.GetUsersRequest
	14, // 27: gateway.Gateway.UpdateUser:input_type -> gateway.UpdateUserRequest
	15, // 28: gateway.Gateway.UpdateCurrentUser:input_type -> gateway.UpdateCurrentUserRequest
	16, // 29: gateway.Gateway.DeleteUser:input_type -> gateway.DeleteUserRequest
	29, // 30: gateway.Gateway.DeleteCurrentUser:input_type -> google.protobuf.Empty
	18, // 31: gateway.Gateway.Deposit:input_type -> gateway.DepositRequest
	19, // 32: gateway.Gateway.Withdraw:input_type -> gateway.WithdrawRequest
	20, // 33: gateway.Gateway.Transfer:input_type -> gateway.TransferRequest
	21, // 34: gateway.Gateway.GetTransactions:input_type -> gateway.GetTransactionsRequest
	1,  // 35: gateway.Gateway.Register:output_type -> gateway.RegisterResponse
	3,  // 36: gateway.Gateway.Login:output_type -> gateway.LoginResponse
	17, // 37: gateway.Gateway.Refresh:output_type -> gateway.RefreshResponse
	29, // 38: gateway.Gateway.Logout:output_type -> google.protobuf.Empty
	7,  // 39: gateway.Gateway.ValidateToken:output_type -> gateway.ValidateTokenResponse
	29, // 40: gateway.Gateway.CreateUser:output_type -> google.protobuf.Empty
	10, // 41: gateway.Gateway.GetUser:output_type -> gateway.GetUserResponse
	11, // 42: gateway.Gateway.GetCurrentUser:output_type -> gateway.GetCurrentUserResponse
	13, // 43: gateway.Gateway.GetUsers:output_type -> gateway.GetUsersResponse
	29, // 44: gateway.Gateway.UpdateUser:output_type -> google.protobuf.Empty
	29, // 45: gateway.Gateway.UpdateCurrentUser:output_type -> google.protobuf.Empty
	29, // 46: gateway.Gateway.DeleteUser:output_type -> google.protobuf.Empty
	29, // 47: gateway.Gateway.DeleteCurrentUser:output_type -> google.protobuf.Empty
	29, // 48: gateway.Gateway.Deposit:output_type -> google.protobuf.Empty
	29, // 49: gateway.Gateway.Withdraw:output_type -> google.protobuf.Empty
	29, // 50: gateway.Gateway.Transfer:output_type -> google.protobuf.Empty
	22, // 51: gateway.Gateway.GetTransactions:output_type -> gateway.GetTransactionsResponse
	35, // [35:52] is the sub-list for method output_type
	18, // [18:35] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_gateway_service_proto_init() }
func file_gateway_service_proto_init() {
	if File_gateway_service_proto != nil {
		return
	}
	file_gateway_service_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_service_proto_rawDesc), len(file_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_service_proto_goTypes,
		DependencyIndexes: file_gateway_service_proto_depIdxs,
		MessageInfos:      file_gateway_service_proto_msgTypes,
	}.Build()
	File_gateway_service_proto = out.File
	file_gateway_service_proto_goTypes = nil
	file_gateway_service_proto_depIdxs = nil
}
